name: codonnier_network
description: "Just add this package in the app and ready to rock the server when it is idle."

version: 1.0.7+8

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6
  dio: ^5.4.1
  http_parser: ^4.0.2
  # Utils
  internet_connection_checker: ^1.0.0+1
  equatable: ^2.0.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1

flutter:
  uses-material-design: true

  module:
    androidX: true
    androidPackage: com.codonnier.codonnier_network
    iosBundleIdentifier: com.codonnier.codonnierNetwork
